# Tuning Defaults
CONNECT_TOL = 0.20
MIN_TOTAL_LENGTH = 0.30
GRID_COLS = 12

EPS_THIN = 0.05
LONG_DIM = 3.0
COMPLEX_MIN = 0.15
MIN_SEGS_FOR_DIGIT = 3

MAX_DOM_DIR = 0.88
MAX_ENDPOINTS_FOR_LINE = 2
ENDPOINT_TOL_SCALE = 1.0

W_FACTOR = 4.0
H_FACTOR = 4.0
LEN_FACTOR = 6.0
AREA_FACTOR = 12.0
MAX_ASPECT = 8.0

SALVAGE_DIST_FACTOR = 0.40
SALVAGE_LONG_SEG_FACTOR = 2.5
SALVAGE_ANGLE_TOL_DEG = 15.0

# Boundary mask defaults
BOUNDARY_LAYER = "boundary_node"
BOUNDARY_MIN_AREA = 1e-6